version: '3'
services:
    slackapp:
        build:
            context: https://github.com/poff-bnff/integration.git
        container_name: slackapp
        command: node /usr/src/slackapp/app.js
        restart: always
        environment:
            NODE_ENV: production
            PORT: 80
            SLACK_BOT_TOKEN:
            SLACK_SIGNING_SECRET:
            GITHUB_TOKEN:
